name: transcendence

services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    tty: true
    ports:
      # - '443:443'
      - '80:80'
    networks:
      - net
      # environment:
      # CERT: /etc/ssl/certs/server.crt
      # CERT_KEY: /etc/ssl/private/server_pkey.pem
      # DOMAIN_NAME: localhost #이후 수정
    depends_on:
      backend:
        condition: service_healthy
        restart: true
  backend:
    container_name: backend
    build: ./backend
    image: backend
    ports:
      - '8000:8000'
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PYTHONPATH=/usr/src/app/pong-game
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./backend:/usr/src/app
    networks:
      - net
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000/health/' ]
      interval: 30s
      retries: 3
      start_period: 5s

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U myuser -d mydatabase' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
networks:
  net:
