# compose는 아직 작업중입니다..
# 각 서비스별로 컨테이너 띄워서 개발하고 나중에 compose로 합치면 될 것 같아요!

name: transcendence

services:
    backend:
        container_name: backend
        image: backend
        build: ./backend
        tty: true
        ports:
            - '8000:8000'
        networks:
            - net
        depends_on:
            database:
                condition: service_healthy
                restart: true
    database:
        image: postgres
        container_name: database
        restart: always
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - net
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'myuser', '-d', 'mydatabase']
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s
        tty: true

volumes:
    postgres_data:

networks:
    net:
