# compose는 아직 작업중입니다..
# 각 서비스별로 컨테이너 띄워서 개발하고 나중에 compose로 합치면 될 것 같아요!

name: transcendence

services:
  frontend:
    build: ./frontend
    ports: 443:443



  backend:
    build: ./backend
    expose: 8000



  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    expose: 3306

