# Generated by Django 4.2.17 on 2025-01-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_name', models.CharField(max_length=50)),
                ('choice', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('other_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('completed', 'Completed')], default='waiting', max_length=10)),
                ('me_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_me', to='sub.user')),
                ('other_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_other', to='sub.user')),
            ],
            options={
                'db_table': 'sub_match',
            },
        ),
    ]
