# Generated by Django 5.1.4 on 2025-01-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_name', models.CharField(max_length=50)),
                ('win_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_choice', models.CharField(blank=True, choices=[('1', 'Rock'), ('2', 'Scissors'), ('3', 'Paper')], max_length=1, null=True)),
                ('other_choice', models.CharField(blank=True, choices=[('1', 'Rock'), ('2', 'Scissors'), ('3', 'Paper')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_me', to='sub.user')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_other', to='sub.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_winner', to='sub.user')),
            ],
            options={
                'db_table': 'sub_match',
            },
        ),
    ]
