# Generated by Django 4.2.17 on 2025-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_remove_match_winner_remove_user_total_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='me',
            new_name='me_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='other',
            new_name='other_id',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('completed', 'Completed')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
