# Generated by Django 5.1.4 on 2025-01-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_alter_match_me_choice_alter_match_other_choice'),
        ('sub', '0004_adminuser'),
    ]

    operations = [
    ]
