# Generated by Django 5.1.4 on 2025-01-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_merge_20250108_0242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
