# Generated by Django 5.1.4 on 2025-01-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0006_delete_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='waiting', max_length=10),
        ),
    ]
